{% set name = "legofy" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/legofy-{{ version }}.tar.gz
  sha256: 3df337047fff12dee9b503ae712534d52ad225e12e0bd0301d9d2f832d0d67be

build:
  number: 1
  noarch: python
  entry_points:
    - legofy = legofy.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - click
    - pillow

test:
  imports:
    - legofy
  commands:
    - pip check
    - legofy --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/JuanPotato/Legofy
  summary: Make images look as if they are made out of 1x1 LEGO blocks
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
